### ISSUE TITLE
Strongly named assemblies

### ISSUE THREAD

**Issue by DanAvni** [StephenClearyArchive/Nito.KitchenSink#1]
Hi,

Any chance for assemblies with strong names? Specifically I need the CRC but other assemblies might prove useful too for others

**Comment by StephenCleary** [comment]
(Sorry for the delay in responding; GitHub did not send me a notification of this issue)

All projects under my "Archive" organization are not maintained. This particular project was moved over from Codeplex, where it had already been inactive for several years.

So, no, sorry, I have no plans to do this. You can strong-name them yourself, though (e.g., using the strong-naming toolkit).
