### ISSUE TITLE
How are these used?

### ISSUE THREAD

**Issue by A9G-Data-Droid** [StephenClearyArchive/Nito.KitchenSink#2]
Is there any documentation on how to use these? I imported the CRC library in to my project and it's not clear how to get a CRC back from it. Isn't there an interface that accepts a byte() or a string to produce a hash? It's not "ComputeHash" as the name suggests.

**Comment by A9G-Data-Droid** [comment]
The issue still stands: These libraries need some documentation. I did finally get it to work.

My problem was that the default "ComputeHash" expects a System.IO.Stream object. If you want to work with a string you have, that is not a stream, it must be passed as a Byte array with an offset and a length. In my case I want the whole string to be hashed so the offset is 0 and the length is the length. Seems overly verbose for this use case. Then to get a string back, in order to compare with other hash strings, I had to convert to a hex string. This came out backwards when compared with other hash functions so I reverse the byte order as I make my final hex string. 

If anyone wants to use this to compare CRC checks from other programs that use the standard ARC version of CRC16 then here is what will work:

```
    Private Sub YourSub
    	Using computeChecksum As New CRC16
            Dim inBytes As Byte() = Encoding.ASCII.GetBytes("Your string here")
            Dim outBytes As Byte() = computeChecksum.ComputeHash(inBytes, 0, inBytes.Count())
            Dim readableHash As String = BytesToHexString(outBytes)
        End Using
    End Sub
        
    Private Shared Function BytesToHexString(ByVal input As ICollection(Of Byte)) As String
	Dim result As New StringBuilder(input.Count * 2)
	Dim part As String
	For Each b As Byte In input
	    part = Hex(b)
	    If part.Length = 1 Then part = "0" & part
	    result.Insert(0, part) ' Reverse byte order
	Next
	Return result.ToString()
    End Function
```

**Comment by StephenCleary** [comment]
(Sorry for the delay in responding; GitHub did not send me a notification of this issue)

All projects under my "Archive" organization are not maintained. This particular project was moved over from Codeplex, where it had already been inactive for several years.

Parts of KitchenSink have moved into other (maintained) libraries. Some parts (including CRC) have not been moved over but are still useful - hence this archived project. Maybe someday when I have time (ha, ha), I'll make CRC into a real maintained project again.

Regarding your specific question, the CRC types derive from `HashAlgorithm`, and are used the same way. `ComputeHash` can take a `Stream`, an array of bytes with index and length, or just an array of bytes. So this should work: `computeChecksum.ComputeHash(inBytes)`.
